services:
  user-service:
    container_name: mzhn-auth-service
    build:
      context: .
    env_file:
      - .env
    environment:
      WAIT_HOSTS: pg:5432
      PG_HOST: pg
      PG_PORT: 5432
      ENV: dev
    depends_on:
      - pg
    ports:
      - "${APP_PORT}:${APP_PORT}"

  pg:
    image: postgres:14.13-alpine3.20
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - ${PG_PORT}:5432

volumes:
  pg_data:
    name: mzhn-auth-pg
